#!/bin/sh
set -e

case "$1" in
    purge)
        # Remove GPG key
        rm -f /etc/apt/trusted.gpg.d/guideos.asc
        
        # Remove sources file
        rm -f /etc/apt/sources.list.d/guideos.sources
        
        # Remove apt configuration
        rm -f /etc/apt/apt.conf.d/90guideos-modernize-sources-notice
        ;;
    
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do
        ;;
    
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
